// This file was auto-generated by Fern from our API Definition.

package client

import (
	core "github.com/fern-api/generator-exec-go/core"
	logging "github.com/fern-api/generator-exec-go/logging"
	readme "github.com/fern-api/generator-exec-go/readme"
	http "net/http"
)

type Client interface {
	Logging() logging.Client
	Readme() readme.Client
}

func NewClient(opts ...core.ClientOption) Client {
	options := core.NewClientOptions()
	for _, opt := range opts {
		opt(options)
	}
	return &client{
		baseURL:       options.BaseURL,
		httpClient:    options.HTTPClient,
		header:        options.ToHeader(),
		loggingClient: logging.NewClient(opts...),
		readmeClient:  readme.NewClient(opts...),
	}
}

type client struct {
	baseURL       string
	httpClient    core.HTTPClient
	header        http.Header
	loggingClient logging.Client
	readmeClient  readme.Client
}

func (c *client) Logging() logging.Client {
	return c.loggingClient
}

func (c *client) Readme() readme.Client {
	return c.readmeClient
}
