// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/fern-api/generator-exec-go/core"
	internal "github.com/fern-api/generator-exec-go/internal"
	logging "github.com/fern-api/generator-exec-go/logging"
	option "github.com/fern-api/generator-exec-go/option"
	readme "github.com/fern-api/generator-exec-go/readme"
)

type Client struct {
	Logging *logging.Client
	Readme  *readme.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Logging: logging.NewClient(options),
		Readme:  readme.NewClient(options),
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
