// Code generated by Fern. DO NOT EDIT.

package logging

import (
	context "context"
	generatorexecgo "github.com/fern-api/generator-exec-go"
	core "github.com/fern-api/generator-exec-go/core"
	internal "github.com/fern-api/generator-exec-go/internal"
	option "github.com/fern-api/generator-exec-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) SendUpdate(
	ctx context.Context,
	taskId generatorexecgo.TaskId,
	request []*generatorexecgo.GeneratorUpdate,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.SendUpdate(
		ctx,
		taskId,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
